# Generated by Django 5.2.12 on 2026-04-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='score',
            field=models.IntegerField(default=100),
        ),
    ]
